### ISSUE TITLE
Portal Metrics New Data source 

### ISSUE THREAD

**Issue by loister72** [logicmonitor/dashboards#2]
There is a new Datasource that was pushed out.  Need to update this Dashboard to align with the new Datasource metrics instance and datapoint.   It will not let me upload the changed JSON.

**Comment by DamienCH** [comment]
I'm interested in the updated version... Hopefully you can upload it at some point.
I just updated the Datasources and it killed my fancy dashboards, now I feel like a moron.

**Comment by loister72** [comment]
> I'm interested in the updated version... Hopefully you can upload it at some point.
> 
> I just updated the Datasources and it killed my fancy dashboards, now I feel like a moron.

You can always edit the data source where the name has changed and re-ping the datapoints.  Sometimes I just pull up the json and find the new data source values and update them in the file.  Then I just reImport. If you are stuck that's all I did to fix this :).

**Comment by kdevilbiss** [comment]
This is resolved in the current Portal Metrics dashboard.
